export const APPLICATION_INFO_RECEIVED = 'APPLICATION_INFO_RECEIVED'
export const FEED_FETCH_FAILURES_CLEAR = 'FEED_FETCH_FAILURES_CLEAR'
export const FEED_FETCH_FAILURES_RECEIVED = 'FEED_FETCH_FAILURES_RECEIVED'
