export const SUBSCRIPTIONS_RECEIVED = 'SUBSCRIPTIONS_RECEIVED'
export const SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED'
export const SUBSCRIPTION_SAVED = 'SUBSCRIPTION_SAVED'
export const SUBSCRIPTION_TAGS_RECEIVED = 'SUBSCRIPTION_TAGS_RECEIVED'
