language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

script: mvn test
after_success:
 - echo "current branch $TRAVIS_BRANCH on jdk version $TRAVIS_JDK_VERSION"
 - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_JDK_VERSION == "openjdk7" ]]; then mvn cobertura:cobertura coveralls:cobertura; fi
