create table entry (
  entry_id bigint generated by default as identity (start with 1),
  entry_content LONGVARCHAR,
  entry_created_at timestamp,
  entry_guid VARCHAR(1000),
  entry_title VARCHAR(1000),
  entry_url VARCHAR(1000),
  entry_feed_id bigint not null,
  primary key (entry_id)
);

create table exclusion_pattern (
  id bigint generated by default as identity (start with 1),
  created_at timestamp,
  hit_count integer,
  pattern varchar(255),
  exclusion_pattern_user_feed_id bigint not null,
  primary key (id)
);

create table feed (
  feed_id bigint generated by default as identity (start with 1),
  feed_created_at timestamp,
  feed_fetched integer,
  feed_last_modified varchar(255),
  result_size_per_fetch integer,
  feed_title VARCHAR(1000) not null,
  feed_url VARCHAR(1000),
  version bigint DEFAULT 0,
  primary key (feed_id)
);

create table fetch_error (
  fetch_error_id bigint generated by default as identity (start with 1),
  fetch_error_created_at timestamp not null,
  fetch_error_message VARCHAR(1000),
  fetch_error_feed_id bigint not null,
  primary key (fetch_error_id)
);

create table user (
  user_id bigint generated by default as identity (start with 1),
  user_email varchar(255),
  user_password varchar(255),
  user_role varchar(255),
  primary key (user_id)
);

create table user_feed (
  user_feed_id bigint generated by default as identity (start with 1),
  user_feed_created_at timestamp,
  user_feed_sum integer,
  last_feed_entry bigint,
  user_feed_tag varchar(255),
  user_feed_title varchar(255),
  version bigint DEFAULT 0,
  user_feed_feed_id bigint not null,
  user_feed_user_id bigint not null,
  primary key (user_feed_id)
);

create table user_feed_entry (
  user_feed_entry_id bigint generated by default as identity (start with 1),
  user_feed_entry_created_at timestamp,
  user_feed_entry_is_read boolean,
  user_feed_entry_tag VARCHAR(1000),
  user_feed_entry_entry_id bigint not null,
  user_feed_entry_user_feed_id bigint not null,
  primary key (user_feed_entry_id)
);

create index entry_title_idx on entry (entry_title);

create index entry_guid_idx on entry (entry_guid);

create index entry_url_idx on entry (entry_url);

alter table entry add constraint FK6o9vg6qcmxfg2xoa6bct64e03 foreign key (entry_feed_id) references feed;

alter table exclusion_pattern add constraint FKibalplakf8eda5420hneeb4b4 foreign key (exclusion_pattern_user_feed_id) references user_feed;

alter table fetch_error add constraint FK8p3n6s1vu0bf7esvlptmg46oo foreign key (fetch_error_feed_id) references feed;

alter table user_feed add constraint FKs91yd3ceqh0q0liu39pkpino1 foreign key (user_feed_feed_id) references feed;

alter table user_feed add constraint FKfv04ls7aanv1xsxk1buon0ybx foreign key (user_feed_user_id) references user;

alter table user_feed_entry add constraint FK9omgp1y5vfqu5dn31f5scsykq foreign key (user_feed_entry_entry_id) references entry;

alter table user_feed_entry add constraint FKor8li8moh8674iex2w9k4wu7b foreign key (user_feed_entry_user_feed_id) references user_feed;
