CREATE INDEX SUBSCRIPTION_ENTRY_SUBSCRIPTION_ID_SEEN_EXCLUDED_IDX ON SUBSCRIPTION_ENTRY (SUBSCRIPTION_ID, SEEN, EXCLUDED);

CREATE VIEW SUBSCRIPTION_VIEW AS
SELECT S.*,
       (SELECT COUNT(1)
        FROM SUBSCRIPTION_ENTRY
        WHERE SUBSCRIPTION_ID = S.ID AND SEEN = FALSE AND EXCLUDED = FALSE) AS UNSEEN,
       (SELECT COUNT(1) FROM FETCH_ERROR WHERE SUBSCRIPTION_ID = S.ID)      AS FETCH_ERROR_COUNT
FROM SUBSCRIPTION S;
