alter table SUBSCRIPTION
  add last_error_message clob;

alter table SUBSCRIPTION
  add last_error_message_datetime TIMESTAMP WITH TIME ZONE;

drop view SUBSCRIPTION_VIEW;

drop table FETCH_ERROR;

create view SUBSCRIPTION_VIEW
    (ID, CREATED_AT, ACCEPTED_FETCH_COUNT, TITLE, URL, LAST_MODIFIED, OVERALL_FETCH_COUNT,
     RESULT_SIZE_PER_FETCH, TAG, COLOR, UNSEEN, LAST_ERROR_MESSAGE_DATETIME)
as
SELECT S.ID,
       S.CREATED_AT,
       S.ACCEPTED_FETCH_COUNT,
       S.TITLE,
       S.URL,
       S.LAST_MODIFIED,
       S.OVERALL_FETCH_COUNT,
       S.RESULT_SIZE_PER_FETCH,
       S.TAG,
       S.COLOR,
       (SELECT COUNT(1)
        FROM PUBLIC.SUBSCRIPTION_ENTRY
        WHERE SUBSCRIPTION_ID = S.ID AND SEEN = FALSE AND EXCLUDED = FALSE) AS UNSEEN,
       S.LAST_ERROR_MESSAGE_DATETIME
FROM PUBLIC.SUBSCRIPTION S;
