create table user_feed_tag (
  user_feed_tag_id bigint generated by default as identity (start with 1),
  user_feed_tag_name varchar(255) not null,
  user_feed_tag_color varchar(255),
  user_feed_tag_created_at timestamp,
  user_feed_tag_user_id bigint not null,
  primary key (user_feed_tag_id)
);

alter table user_feed_tag add constraint user_feed_tag_user_id_fk foreign key (user_feed_tag_user_id) references user on delete cascade;

alter table user_feed add user_feed_user_feed_tag_id bigint null;

alter table user_feed add constraint user_feed_user_feed_tag_id_fk foreign key (user_feed_user_feed_tag_id) references user_feed_tag (user_feed_tag_id) on delete set null;

create unique index user_feed_tag_user_feed_tag_user_feed_tag_user_id_uidx on user_feed_tag (user_feed_tag_name, user_feed_tag_user_id);

insert into user_feed_tag (
  user_feed_tag_name,
  user_feed_tag_user_id,
  user_feed_tag_created_at
) (select
    user_feed_tag,
    user_feed_user_id,
    now()
  from user_feed
    where user_feed_tag is not null
    group by user_feed_tag, user_feed_user_id
);

update user_feed as uf
  set user_feed_user_feed_tag_id = (
    select
      user_feed_tag_id
    from user_feed_tag as uft
      where uf.user_feed_user_id = uft.user_feed_tag_user_id
      and uf.user_feed_tag = uft.user_feed_tag_name
  );

alter table user_feed drop user_feed_tag;
