CREATE FUNCTION MIGRATION_SPLIT_TAGS(IN id BIGINT)
  RETURNS VARCHAR(100) ARRAY
  READS SQL DATA
BEGIN ATOMIC
  DECLARE tags VARCHAR(100) ARRAY;
  SELECT
    REGEXP_SUBSTRING_ARRAY(USER_FEED_ENTRY_TAG, '[\p{Graph}&&[^,|\ ]]+') INTO tags
  FROM USER_FEED_ENTRY
    WHERE USER_FEED_ENTRY_TAG IS NOT NULL AND USER_FEED_ENTRY_ID = id;
  RETURN tags;
END;

CREATE TABLE USER_FEED_ENTRY_TAGS (
  USER_FEED_ENTRY_ID, TAG
) AS (
    SELECT
      DISTINCT USER_FEED_ENTRY_ID, tags
    FROM (
      SELECT
        ufe.USER_FEED_ENTRY_ID, v.tags as tags
      FROM USER_FEED_ENTRY as ufe, UNNEST(MIGRATION_SPLIT_TAGS(ufe.USER_FEED_ENTRY_ID)) v (tags)
    )
) WITH DATA;

ALTER TABLE USER_FEED_ENTRY_TAGS ALTER COLUMN USER_FEED_ENTRY_ID SET NOT NULL;
ALTER TABLE USER_FEED_ENTRY_TAGS ALTER COLUMN TAG SET NOT NULL;
CREATE UNIQUE INDEX USER_FEED_ENTRY_TAGS_ID_TAG_UIDX ON USER_FEED_ENTRY_TAGS (USER_FEED_ENTRY_ID, TAG);

ALTER TABLE USER_FEED_ENTRY_TAGS
  ADD CONSTRAINT FK_USER_FEED_ENTRY_ID
  FOREIGN KEY (USER_FEED_ENTRY_ID) REFERENCES USER_FEED_ENTRY
  ON DELETE CASCADE;

DROP FUNCTION MIGRATION_SPLIT_TAGS;

ALTER TABLE USER_FEED_ENTRY DROP COLUMN USER_FEED_ENTRY_TAG;
