DELETE
FROM USER_FEED_TAG
WHERE USER_FEED_TAG_ID IN (
    SELECT uft.USER_FEED_TAG_ID
    FROM USER_FEED_TAG uft
             LEFT JOIN USER_FEED uf
                       ON uf.USER_FEED_USER_FEED_TAG_ID = uft.USER_FEED_TAG_ID
    WHERE uf.USER_FEED_ID IS NULL
);
