import 'angular'
import 'angular-sanitize'
import '@uirouter/angularjs'
import 'angular-messages'
import 'angular-sanitize'
import 'angular-animate'
import 'angular-aria'
import 'redux'
import 'redux-thunk'
import 'reselect'
import 'ng-redux'

import 'angular-material/modules/js/button/button'
import 'angular-material/modules/js/button/button.css'
import 'angular-material/modules/js/core/core'
import 'angular-material/modules/js/core/core.css'
import 'angular-material/modules/js/list/list'
import 'angular-material/modules/js/list/list.css'
