import 'angular'
import 'angular-sanitize'
import '@uirouter/angularjs'
import 'angular-messages'
import 'angular-sanitize'
import 'redux'
import 'redux-thunk'
import 'reselect'
import 'ng-redux'
import 'timeago.js'

import 'angular-material/modules/js/core/core.css'
